# Morgan Stanley makes this available to you under the Apache License, Version 2.0 (the "License"). You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0. See the NOTICE file distributed with this work for additional information regarding copyright ownership. Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.  

# This workflow will do a clean install of node dependencies, build the source code and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, nx-monorepo ]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

name: CI

jobs:
  build:
    env:
      COMPOSEUI_SKIP_DOWNLOAD: 'true'
      DOTNET_CONSOLE_ANSI_COLOR: 'true'
      NX_VERBOSE_LOGGING: 'true'
      NX_API_LOG_LEVEL: 'DEBUG'

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        node-version: [ '20.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
        COMPOSEUI_SKIP_DOWNLOAD: ${{env.COMPOSEUI_SKIP_DOWNLOAD}}

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install/Restore NPM/Nuget dependencies
      run: npm ci

    - name: Information about directory
      run: | 
           npm -v
           node -v
           dir

    - name: Build Projects
      run: npx nx run-many -t build --verbose
    
    - name: Test Projects
      run: npx nx run-many -t test --verbose

    - name: Codecov
      uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
    - name: Pack .NET
      run: |
           powershell ./build/dotnet-pack.ps1

    - name: Upload Nuget Packages
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: packages
        path: ${{ github.workspace }}/packages

    - name: Upload Shell Binaries
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: shell-binaries
        path: ${{ github.workspace }}/src/shell/dotnet/Shell/bin/Release/net6.0-windows/