on:
  release:
    types: [ published ]
    branches: [ main ]

  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

name: Release

jobs:
  build:
    uses: ./.github/workflows/continuous-integration.yml

  upload:
    name: Upload Release Asset
    needs: build
    runs-on: windows-latest

    steps:
      # Using shared artifact from build workflow
      - name: Set environment variable on feature branch
        if: github.ref != 'refs/heads/main'
        env:
          github.ref_name: test
        run:  |
              echo "ENV variable: {{ github.ref_name }}"

      - name: Download Artifact
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: shell-binaries
          path: ${{ github.workspace }}/shell-binaries
    
      - name: Display structure of downloaded files
        run: Get-ChildItem -Recurse
        working-directory: ${{ github.workspace }}/shell-binaries

      - name: Compress
        if: github.ref == 'refs/heads/main'
        run:  |
              echo "Path: ${{ github.workspace }}/shell-binaries/"
              echo "RefName: ${{ github.ref_name }}"
              Compress-Archive -Path  ${{ github.workspace }}/shell-binaries/* -DestinationPath ./composeui-${{ github.ref_name }}-win32.zip

      - name: Upload Release Asset
        id: upload-release-asset
        if: github.ref == 'refs/heads/main
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./composeui-${{ github.ref_name }}-win32.zip
          asset_name: composeui-${{ github.ref_name }}-win32.zip
          asset_content_type: application/zip
          
  deploy-npm:
    name: Publish Package to npmjs
    runs-on: windows-latest
    needs: upload
      
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: |
             dir
             npm ci
             npm run build
             npm whoami
             npm publish --dry-run --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ${{ github.workspace }}/src/shell/js/composeui-node-launcher/
